name: dr_purple
description: A Flutter project for the customers of a medical center called Mr. Purple.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.1.1
  easy_localization: ^3.0.2
  shared_preferences: ^2.1.1
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  go_router: ^7.1.1
  fluttertoast: ^8.2.2
  analyzer: ^5.10.0
  dio: ^5.1.2
  pretty_dio_logger: ^1.3.1
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.3
  permission_handler: ^10.2.0
  cached_network_image: ^3.2.3
  pinput: ^2.2.31
  awesome_dialog: ^3.0.2
  flutter_logs: ^2.1.10
  shimmer: ^3.0.0
  flutter_local_notifications: ^14.1.0
  flutter_uploader: ^3.0.0-beta.4
  flutter_svg: ^2.0.6
  scrollable_positioned_list: ^0.3.8
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.7+5
  widget_and_text_animator: ^1.0.9
  nb_utils: ^5.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  freezed: ^2.3.4

dependency_overrides:
  intl: ^0.18.1
  win32: ^5.0.2
  http: ^1.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/flags/
    - assets/translation/
    - assets/icons/
    - assets/images/
    - assets/images/get_started/
    - assets/images/auth/

  fonts:
    - family: Century-Gothic
      fonts:
        - asset: assets/fonts/Century-Gothic-Bold.ttf
        - asset: assets/fonts/Century-Gothic-Regular.ttf